// Code generated by NEAR contract generator. DO NOT EDIT.

package main

import (
	contractBuilder "github.com/vlmoon99/near-sdk-go/contract"
	"github.com/vlmoon99/near-sdk-go/env"
	"github.com/vlmoon99/near-sdk-go/borsh"
	"github.com/vlmoon99/near-sdk-go/json"
 	encodingJson "encoding/json"
	"strconv"
)

// ===== From: counter2.go =====
func (c *Counter) Test12() string {
	return ""
}

func (c *Counter) Test22(value int) int {
	return 0
}

func (c *Counter) Test32(msg string) string {
	return ""
}

func (c *Counter) Test42() {
	// internal logic
}

func (c *Counter) Test52(key string) int {
	return 0
}

func (c *Counter) Test62(a, b int) int {
	return 0
}

func (c *Counter) Test72() string {
	return ""
}

func (c *Counter) Test82(flag bool) {
	// internal logic
}

func (c *Counter) Test92() bool {
	return false
}

func (c *Counter) Test102(name string, amount int) string {
	return ""
}

// ===== From: func1.go =====
func TestIdea() bool {
	builder := json.NewBuilder()
	expected := `{"age":30}`
	result := string(builder.AddInt("age", 30).Build())
	if result != expected {
		env.LogString("Error")
	}
	return true
}

type MyData struct {
    Name string
    Age  int
}

func (c *Counter) ProcessData(data MyData) string {
    // Works!
	return data.Name
}

// ===== From: main.go =====
type Counter struct {
    Count int
	Owner string
}

// ===== From: modules/counter.go =====
func (c *Counter) GetCount() int {
	return c.Count
}

func (c *Counter) Increment(amount int) int {
	c.Count += amount
	return c.Count
}

func (c *Counter) Decrement(amount int) int {
	c.Count -= amount
	return c.Count
}

func (c *Counter) Reset() string {
	c.Count = 0
	return "Counter reset"
}

// ===== From: modules/counter1.go =====
func (c *Counter) Test1() string {
	return ""
}

func (c *Counter) Test2(value int) int {
	return 0
}

func (c *Counter) Test3(msg string) string {
	return ""
}

func (c *Counter) Test4() {
	// internal logic
}

func (c *Counter) Test5(key string) int {
	return 0
}

func (c *Counter) Test6(a, b int) int {
	return 0
}

func (c *Counter) Test7() string {
	return ""
}

func (c *Counter) Test8(flag bool) {
	// internal logic
}

func (c *Counter) Test9() bool {
	return TestIdea();
}

func (c *Counter) Test10(name string, amount int) string {
	return ""
}

// ===== From: modules/sub_module1/counter4.go =====
func (c *Counter) Test14() string {
	return ""
}

func (c *Counter) Test24(value int) int {
	return 0
}

func (c *Counter) Test34(msg string) string {
	return ""
}

func (c *Counter) Test44() {
	// internal logic
}

func (c *Counter) Test54(key string) int {
	return 0
}

func (c *Counter) Test64(a, b int) int {
	return 0
}

func (c *Counter) Test74() string {
	return ""
}

func (c *Counter) Test84(flag bool) {
	// internal logic
}

func (c *Counter) Test94() bool {
	return false
}

func (c *Counter) Test104(name string, amount int) string {
	return ""
}

// ===== From: modules/sub_module2/counter3.go =====
func (c *Counter) Test13() string {
	return ""
}

func (c *Counter) Test23(value int) int {
	return 0
}

func (c *Counter) Test33(msg string) string {
	return ""
}

func (c *Counter) Test43() {
	// internal logic
}

func (c *Counter) Test53(key string) int {
	return 0
}

func (c *Counter) Test63(a, b int) int {
	return 0
}

func (c *Counter) Test73() string {
	return ""
}

func (c *Counter) Test83(flag bool) {
	// internal logic
}

func (c *Counter) Test93() bool {
	return false
}

func (c *Counter) Test103(name string, amount int) string {
	return ""
}

// getState reads and deserializes Counter from blockchain
func getState() *Counter {
	val, err := env.StateRead()
	if err != nil || len(val) == 0 {
		return &Counter{}
	}

	var state Counter
	err = borsh.Deserialize(val, &state)
	if err != nil {
		env.PanicStr("Failed to deserialize state")
	}

	return &state
}

// setState serializes and writes Counter to blockchain
func setState(state *Counter) {
	val, err := borsh.Serialize(state)
	if err != nil {
		env.PanicStr("Failed to serialize state")
	}

	err = env.StateWrite(val)
	if err != nil {
		env.PanicStr("Failed to write state")
	}
}

// ===== Generated Exports =====
// Export: test12 (from counter2.go)
//go:export test12
func test12() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test12()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test22 (from counter2.go)
//go:export test22
func test22() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		valueInt64, err := input.JSON.GetInt("value")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		value := int(valueInt64)

		// Call method
		result := state.Test22(value)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test32 (from counter2.go)
//go:export test32
func test32() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 0.0005 NEAR
		if !validatePayment("0.0005") {
			env.PanicStr("Insufficient payment")
		}

		msg, err := input.JSON.GetString("msg")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test32(msg)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test52 (from counter2.go)
//go:export test52
func test52() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		key, err := input.JSON.GetString("key")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test52(key)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test62 (from counter2.go)
//go:export test62
func test62() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		aInt64, err := input.JSON.GetInt("a")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		a := int(aInt64)

		bInt64, err := input.JSON.GetInt("b")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		b := int(bInt64)

		// Call method
		result := state.Test62(a, b)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test72 (from counter2.go)
//go:export test72
func test72() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 1 NEAR
		if !validatePayment("1") {
			env.PanicStr("Insufficient payment")
		}

		// Call method
		result := state.Test72()

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test92 (from counter2.go)
//go:export test92
func test92() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test92()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test102 (from counter2.go)
//go:export test102
func test102() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		name, err := input.JSON.GetString("name")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Test102(name, amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

type MyDataJSON struct {
    Name string `json:"name"`
    Age  int `json:"age"`
}

func decodeInputJSON(data []byte) (MyData, error) {
    var tmp MyDataJSON
    if err := encodingJson.Unmarshal(data, &tmp); err != nil {
        return MyData{}, err
    }

    return MyData{
        Name: tmp.Name,
        Age:  tmp.Age,
    }, nil
}


//go:export process_data
func process_data() {
    contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
        env.LogString("input len = " + strconv.Itoa(len(input.Data)))

        data, err := decodeInputJSON(input.Data)
        if err != nil {
            env.PanicStr("Invalid JSON input")
        }

        // now data is SAFE, typed, deterministic
        contractBuilder.ReturnValue(data.Name)
        return nil
    })
}

// // Export: process_data (from func1.go)
// //go:export process_data
// func process_data() {
// 	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
// 		// Read state
// 		// state := getState()

// 		// Parse complex type: MyData
// 		dataBytes := input.Data

// 		env.LogString(string(dataBytes))

// 		var data MyData
// 		err := borsh.Deserialize(input.Data, &data)
// 		if err != nil {
// 			env.PanicStr("Failed to deserialize parameter")
// 		}


// 		// // Call method
// 		// result := state.ProcessData(data)

// 		contractBuilder.ReturnValue(string(dataBytes))
// 		return nil
// 	})
// }

// Export: get_count (from modules/counter.go)
//go:export get_count
func get_count() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.GetCount()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: increment (from modules/counter.go)
//go:export increment
func increment() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Increment(amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: decrement (from modules/counter.go)
//go:export decrement
func decrement() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Decrement(amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: reset (from modules/counter.go)
//go:export reset
func reset() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 0.001 NEAR
		if !validatePayment("0.001") {
			env.PanicStr("Insufficient payment")
		}

		// Call method
		result := state.Reset()

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test1 (from modules/counter1.go)
//go:export test1
func test1() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test1()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test2 (from modules/counter1.go)
//go:export test2
func test2() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		valueInt64, err := input.JSON.GetInt("value")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		value := int(valueInt64)

		// Call method
		result := state.Test2(value)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test3 (from modules/counter1.go)
//go:export test3
func test3() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 0.0005 NEAR
		if !validatePayment("0.0005") {
			env.PanicStr("Insufficient payment")
		}

		msg, err := input.JSON.GetString("msg")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test3(msg)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test5 (from modules/counter1.go)
//go:export test5
func test5() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		key, err := input.JSON.GetString("key")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test5(key)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test6 (from modules/counter1.go)
//go:export test6
func test6() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		aInt64, err := input.JSON.GetInt("a")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		a := int(aInt64)

		bInt64, err := input.JSON.GetInt("b")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		b := int(bInt64)

		// Call method
		result := state.Test6(a, b)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test7 (from modules/counter1.go)
//go:export test7
func test7() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 1 NEAR
		if !validatePayment("1") {
			env.PanicStr("Insufficient payment")
		}

		// Call method
		result := state.Test7()

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test9 (from modules/counter1.go)
//go:export test9
func test9() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test9()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test10 (from modules/counter1.go)
//go:export test10
func test10() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		name, err := input.JSON.GetString("name")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Test10(name, amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test14 (from modules/sub_module1/counter4.go)
//go:export test14
func test14() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test14()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test24 (from modules/sub_module1/counter4.go)
//go:export test24
func test24() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		valueInt64, err := input.JSON.GetInt("value")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		value := int(valueInt64)

		// Call method
		result := state.Test24(value)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test34 (from modules/sub_module1/counter4.go)
//go:export test34
func test34() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 0.0005 NEAR
		if !validatePayment("0.0005") {
			env.PanicStr("Insufficient payment")
		}

		msg, err := input.JSON.GetString("msg")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test34(msg)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test54 (from modules/sub_module1/counter4.go)
//go:export test54
func test54() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		key, err := input.JSON.GetString("key")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test54(key)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test64 (from modules/sub_module1/counter4.go)
//go:export test64
func test64() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		aInt64, err := input.JSON.GetInt("a")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		a := int(aInt64)

		bInt64, err := input.JSON.GetInt("b")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		b := int(bInt64)

		// Call method
		result := state.Test64(a, b)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test74 (from modules/sub_module1/counter4.go)
//go:export test74
func test74() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 1 NEAR
		if !validatePayment("1") {
			env.PanicStr("Insufficient payment")
		}

		// Call method
		result := state.Test74()

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test94 (from modules/sub_module1/counter4.go)
//go:export test94
func test94() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test94()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test104 (from modules/sub_module1/counter4.go)
//go:export test104
func test104() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		name, err := input.JSON.GetString("name")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Test104(name, amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test13 (from modules/sub_module2/counter3.go)
//go:export test13
func test13() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test13()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test23 (from modules/sub_module2/counter3.go)
//go:export test23
func test23() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		valueInt64, err := input.JSON.GetInt("value")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		value := int(valueInt64)

		// Call method
		result := state.Test23(value)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test33 (from modules/sub_module2/counter3.go)
//go:export test33
func test33() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 0.0005 NEAR
		if !validatePayment("0.0005") {
			env.PanicStr("Insufficient payment")
		}

		msg, err := input.JSON.GetString("msg")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test33(msg)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test53 (from modules/sub_module2/counter3.go)
//go:export test53
func test53() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		key, err := input.JSON.GetString("key")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		// Call method
		result := state.Test53(key)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test63 (from modules/sub_module2/counter3.go)
//go:export test63
func test63() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		aInt64, err := input.JSON.GetInt("a")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		a := int(aInt64)

		bInt64, err := input.JSON.GetInt("b")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		b := int(bInt64)

		// Call method
		result := state.Test63(a, b)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test73 (from modules/sub_module2/counter3.go)
//go:export test73
func test73() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Validate payment: 1 NEAR
		if !validatePayment("1") {
			env.PanicStr("Insufficient payment")
		}

		// Call method
		result := state.Test73()

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test93 (from modules/sub_module2/counter3.go)
//go:export test93
func test93() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		// Call method
		result := state.Test93()

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// Export: test103 (from modules/sub_module2/counter3.go)
//go:export test103
func test103() {
	contractBuilder.HandleClientJSONInput(func(input *contractBuilder.ContractInput) error {
		// Read state
		state := getState()

		name, err := input.JSON.GetString("name")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}

		amountInt64, err := input.JSON.GetInt("amount")
		if err != nil {
			env.PanicStr("Failed to parse parameter")
		}
		amount := int(amountInt64)

		// Call method
		result := state.Test103(name, amount)

		// Save state
		setState(state)

		contractBuilder.ReturnValue(result)
		return nil
	})
}

// ===== Helper Functions =====
// validatePayment checks if sufficient NEAR is attached
func validatePayment(minDeposit string) bool {
	// TODO: Implement payment validation
	return true
}
